argo:
  env: dev
  vaultPrefix: secret/dsde/monster/dev/ingest/hca
  namespace: hca-mvp
  artifactBucket: broad-dsp-monster-hca-dev-argo-archive
notification:
  onlyOnFailure: false
  vaultSecret:
    path: secret/dsde/monster/dev/ingest/hca/slack-notifier
    key: url