enable: true
schedule: '0 13 * * *'
argo:
  env: dev
  vaultPrefix: secret/dsde/monster/dev/command-center
  namespace: clinvar
  artifactBucket: broad-dsp-monster-clingen-dev-argo-archive
chart:
  git: true
  ref: master
repo:
  url: https://jade.datarepo-dev.broadinstitute.org
  dataProject: broad-jade-dev-data
  datasetName: monster_clinvar
  datasetId: a1fc768d-b58a-4996-8210-11581e9a2ce9
  profileId: b94944a9-df3d-4b35-b573-c7d9b249ea52
notification:
  onlyOnFailure: false
  vaultSecret:
    path: secret/dsde/monster/dev/slack-notifier
    key: monster-ci-url
